/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.8 public/models/skimmerskiffsixteen.glb --keepmeshes
*/

import React, { useEffect, useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import gsap from "gsap";
import { useThree } from "@react-three/fiber";
import useColorStore from "../Utils/store";

export function Ski16({ props }) {
  const { nodes, materials } = useGLTF("./models/skimmerskiffsixteen.glb");
  const { colors, activeState, setActiveState } = useColorStore();
  const { camera } = useThree();
  const primFencRef = useRef();
  const secFencRef = useRef();

  console.log(colors["Power Pole"]);

  //  useEffect(() => {
  //   switch (activeState) {
  //     case 0:
  //       gsap.to(camera.position, {
  //         x: 4,
  //         y: 2.5,
  //         z: 5.5,
  //         duration: 2,
  //         ease: "power.easeOut",
  //         onComplete: () => {
  //           setTimeout(() => {}, 100);
  //         },
  //         onStart: () => {
  //           gsap.to(camera.rotation, {
  //             x: 0,
  //             y: 0,
  //             z: 0,
  //           });
  //         },
  //       });
  //       break;

  //     case "Hull Color":
  //       gsap.to(camera.position, {
  //         x: 0,
  //         y: -2.2,
  //         z: 6.5,
  //         duration: 3,
  //         ease: "power.easeOut",

  //         onUpdate: () => {
  //           camera.lookAt(...primFencRef.current.position);
  //         },
  //       });
  //       break;

  //       case "Power Pole":
  //        gsap.to(camera.position, {
  //          x: 3.57,
  //          y: 1.7,
  //          z: 5,
  //          duration: 2,
  //          ease: "power.easeOut",

  //          onUpdate: () => {
  //            camera.lookAt(...primFencRef.current.position);
  //          },
  //        });
  //        break;

  //   }
  // }, [activeState]);

  return (
    <group {...props} dispose={null}>
      <group position={[0.003, 0.47, 0]}>
        <group position={[0.151, -0.638, 0]}>
          <mesh
            geometry={nodes.StaticMeshActor_197_StaticMeshComponent0.geometry}
            material={materials.Aluminum_Blurry__0}
            position={[-1.807, 0, 0.16]}
          />
          <mesh
            geometry={nodes.StaticMeshActor_198_StaticMeshComponent0.geometry}
            material={materials.Aluminum_Blurry__0}
            position={[1.296, 0, 0.715]}
            rotation={[0, -1.571, 0]}
          />
          <mesh
            geometry={nodes.StaticMeshActor_199_StaticMeshComponent0.geometry}
            material={materials.Aluminum_Blurry__0}
            position={[1.644, 0, 0.715]}
            rotation={[0, -1.571, 0]}
          />
          <mesh
            geometry={nodes.StaticMeshActor_200_StaticMeshComponent0.geometry}
            material={materials.Aluminum_Blurry__0}
            position={[1.807, 0, 0.126]}
          />
          <mesh
            geometry={nodes.StaticMeshActor_202_StaticMeshComponent0.geometry}
            material={materials.Aluminum_Blurry__0}
            position={[-1.807, 0, -0.16]}
            rotation={[0, 0, -Math.PI]}
            scale={-1}
          />
          <mesh
            geometry={nodes.StaticMeshActor_203_StaticMeshComponent0.geometry}
            material={materials.Aluminum_Blurry__0}
            position={[1.296, 0, -0.715]}
            rotation={[-Math.PI, 1.571, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.StaticMeshActor_204_StaticMeshComponent0.geometry}
            material={materials.Aluminum_Blurry__0}
            position={[1.643, 0, -0.715]}
            rotation={[-Math.PI, 1.571, 0]}
            scale={-1}
          />
          <mesh
            geometry={nodes.StaticMeshActor_205_StaticMeshComponent0.geometry}
            material={materials.Aluminum_Blurry__0}
            position={[1.807, 0, -0.127]}
            rotation={[0, 0, -Math.PI]}
            scale={-1}
          />
          <mesh
            geometry={nodes.StaticMeshActor_201_StaticMeshComponent0.geometry}
            material={materials.Aluminum_Blurry__0}
            position={[1.447, 0, 0.057]}
            scale={[0.726, 0.726, 0.531]}
          />
          <mesh
            geometry={nodes.StaticMeshActor_206_StaticMeshComponent0.geometry}
            material={materials.Aluminum_Blurry__0}
            position={[1.447, 0, -0.057]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.726, -0.726, -0.531]}
          />
        </group>
        <mesh
          geometry={nodes.StaticMeshActor_0_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_white__0}
          position={[-0.007, -0.677, 0]}
        />
        <mesh
          name='Hull Color'
          ref={primFencRef}
          material-color={colors["Hull Color"]}
          geometry={nodes.StaticMeshActor_1_StaticMeshComponent0.geometry}
          material={materials.Carpaint_Matte_Capri_Blue__0}
          position={[-0.007, -0.665, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={-1}
        />
        <mesh
          geometry={nodes.StaticMeshActor_2_StaticMeshComponent0.geometry}
          material={materials.Plastic_Metallic_Black__0}
          position={[1.465, -0.722, 0.774]}
          rotation={[1.881, -0.092, -0.278]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_3_StaticMeshComponent0.geometry}
          material={materials.Plastic_Metallic_Black__0}
          position={[1.465, -0.722, -0.774]}
          rotation={[-1.881, 0.092, 2.864]}
          scale={-1}
        />
        <group
          position={[-0.757, -0.711, 0.783]}
          rotation={[1.909, 0.024, 0.068]}
        >
          <mesh
            geometry={nodes.Cylinder003.geometry}
            material={materials.Plastic_Metallic_Black__0}
          />
          <mesh
            geometry={nodes.Cylinder003_1.geometry}
            material={materials.Aluminum_Blurry__0}
          />
        </group>
        <mesh
          geometry={nodes.StaticMeshActor_5_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[-1.995, -0.72, 0.418]}
          rotation={[1.928, 0.194, 0.477]}
          scale={[1.135, 1, 0.72]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_7_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[-1.995, -0.72, -0.418]}
          rotation={[-1.928, -0.194, -2.664]}
          scale={[-1.135, -1, -0.72]}
        />
        <group
          position={[-0.757, -0.711, -0.783]}
          rotation={[-1.909, -0.024, -3.073]}
          scale={-1}
        >
          <mesh
            geometry={nodes.Cylinder005.geometry}
            material={materials.Plastic_Metallic_Black__0}
          />
          <mesh
            geometry={nodes.Cylinder005_1.geometry}
            material={materials.Aluminum_Blurry__0}
          />
        </group>
        <mesh
          geometry={nodes.StaticMeshActor_10_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[-0.007, -0.677, 0]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_11_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[-0.007, -0.678, 0]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_12_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[2.204, -0.664, 0.213]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[1, 1, 0.877]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_13_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[2.204, -0.664, -0.214]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[-1, -1, -0.877]}
          visible={false}
        />
        <mesh
          geometry={nodes.StaticMeshActor_14_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_white__0}
          position={[-1.323, -0.664, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={-0.996}
        />
        <group
          position={[-0.003, -0.787, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1.015, -1, -1]}
        >
          <mesh
            geometry={nodes.Line006.geometry}
            material={materials.Plastic_Simple_Blurry_white__0}
          />
          <mesh
            geometry={nodes.Line006_1.geometry}
            material={materials.Plastic_Simple_Blurry_grey__0}
          />
        </group>
        <mesh
          geometry={nodes.StaticMeshActor_16_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_white__0}
          position={[1.623, -0.664, 0.599]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_19_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_white__0}
          position={[1.623, -0.664, -0.599]}
          rotation={[0, 0, -Math.PI]}
          scale={-1}
        />
        <mesh
          geometry={nodes.StaticMeshActor_17_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_white__0}
          position={[1.809, -0.677, 0]}
        />
        <group position={[1.476, -0.644, 0]} scale={[0.998, 0.998, 1.715]}>
          <mesh
            geometry={nodes.Object001.geometry}
            material={materials.Plastic_Simple_Blurry_Blue__0}
          />
          <mesh
            geometry={nodes.Object001_1.geometry}
            material={materials.Plastic_Simple_Blurry_Black__0}
          />
        </group>
        <mesh
          geometry={nodes.StaticMeshActor_20_StaticMeshComponent0.geometry}
          material={materials.Plastic_Translucent_01_White__0}
          position={[1.476, -0.64, 0]}
          scale={[0.998, 0.998, 1.715]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_21_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[-0.007, -0.677, 0]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_23_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[-0.007, -0.677, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={-1}
        />
        <mesh
          geometry={nodes.StaticMeshActor_22_StaticMeshComponent0.geometry}
          material={materials.Object_f38cbb3f_7b27_4da8_bd73_27678236849c}
          position={[-0.007, -0.677, -0.458]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_24_StaticMeshComponent0.geometry}
          material={materials.Object_f38cbb3f_7b27_4da8_bd73_27678236849c}
          position={[-0.007, -0.677, 0.458]}
          rotation={[0, 0, -Math.PI]}
          scale={-1}
        />
        <mesh
          geometry={nodes.StaticMeshActor_25_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[-1.323, -0.664, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={-0.996}
        />
        <mesh
          geometry={nodes.StaticMeshActor_27_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[-1.323, -0.664, 0]}
          scale={0.996}
        />
        <mesh
          geometry={nodes.StaticMeshActor_26_StaticMeshComponent0.geometry}
          material={materials.Object_f38cbb3f_7b27_4da8_bd73_27678236849c}
          position={[-1.323, -0.689, -0.144]}
          rotation={[0, 0, -Math.PI]}
          scale={-0.996}
        />
        <mesh
          geometry={nodes.StaticMeshActor_28_StaticMeshComponent0.geometry}
          material={materials.Object_f38cbb3f_7b27_4da8_bd73_27678236849c}
          position={[-1.323, -0.689, 0.144]}
          scale={0.996}
        />
        <mesh
          geometry={nodes.StaticMeshActor_29_StaticMeshComponent0.geometry}
          material={materials.Object_f38cbb3f_7b27_4da8_bd73_27678236849c}
          position={[1.623, -0.664, 0.599]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_30_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[1.623, -0.664, 0.599]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_32_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[1.623, -0.664, -0.599]}
          rotation={[0, 0, -Math.PI]}
          scale={-1}
        />
        <mesh
          geometry={nodes.StaticMeshActor_31_StaticMeshComponent0.geometry}
          material={materials.Object_f38cbb3f_7b27_4da8_bd73_27678236849c}
          position={[1.623, -0.664, -0.599]}
          rotation={[0, 0, -Math.PI]}
          scale={-1}
        />
        <group position={[1.72, -0.636, 0]} scale={0.99}>
          <mesh
            geometry={nodes.Cylinder010.geometry}
            material={materials.Plastic_Simple_Blurry_Black__0}
          />
          <mesh
            geometry={nodes.Cylinder010_1.geometry}
            material={materials.Aluminum_Blurry__0}
          />
        </group>
        <group
          position={[1.629, -0.636, 0.534]}
          rotation={[0, -1.571, 0]}
          scale={[0.99, 0.669, 0.99]}
        >
          <mesh
            geometry={nodes.Cylinder012.geometry}
            material={materials.Plastic_Simple_Blurry_Black__0}
          />
          <mesh
            geometry={nodes.Cylinder012_1.geometry}
            material={materials.Aluminum_Blurry__0}
          />
        </group>
        <group
          position={[-1.054, -0.636, 0]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.99}
        >
          <mesh
            geometry={nodes.Cylinder014.geometry}
            material={materials.Plastic_Simple_Blurry_Black__0}
          />
          <mesh
            geometry={nodes.Cylinder014_1.geometry}
            material={materials.Aluminum_Blurry__0}
          />
        </group>
        <group
          position={[1.629, -0.636, -0.534]}
          rotation={[-Math.PI, 1.571, 0]}
          scale={[-0.99, -0.601, -0.99]}
        >
          <mesh
            geometry={nodes.Cylinder016.geometry}
            material={materials.Plastic_Simple_Blurry_Black__0}
          />
          <mesh
            geometry={nodes.Cylinder016_1.geometry}
            material={materials.Aluminum_Blurry__0}
          />
        </group>
        <mesh
          geometry={nodes.StaticMeshActor_37_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[1.389, -0.639, 0]}
          scale={[1, 0.389, 1]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_38_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_white__0}
          position={[-2.431, -0.64, -0.031]}
          rotation={[0, -0.611, 0]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_39_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_white__0}
          position={[-2.422, -0.616, -0.024]}
          rotation={[0, -0.611, 0]}
        />
        <group position={[-2.594, -0.616, -0.215]} rotation={[0, -0.611, 0]}>
          <mesh
            geometry={nodes.Box013.geometry}
            material={materials.Plastic_Simple_Blurry_Black__0}
          />
          <mesh
            geometry={nodes.Box013_1.geometry}
            material={materials.Plastic_Simple_Blurry_white__0}
          />
        </group>
        <mesh
          geometry={nodes.StaticMeshActor_41_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[-2.566, -0.586, -0.174]}
          rotation={[Math.PI / 2, 0, 0.611]}
        />
        <group
          position={[-2.527, -0.474, -0.332]}
          rotation={[1.555, -0.011, 0.611]}
        >
          <mesh
            geometry={nodes.Cylinder019.geometry}
            material={materials.Plastic_Metallic_Black__0}
          />
          <mesh
            geometry={nodes.Cylinder019_1.geometry}
            material={materials.Plastic_Simple_Blurry_white__0}
          />
        </group>
        <mesh
          geometry={nodes.StaticMeshActor_43_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[-2.602, -0.527, -0.219]}
          rotation={[0, -0.611, 0]}
          scale={[1, 1, 0.684]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_44_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[-2.665, -0.527, -0.128]}
          rotation={[0, -0.611, 0]}
          scale={[1, 1, 0.684]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_45_StaticMeshComponent0.geometry}
          material={materials.Plastic_Metallic_Black__0}
          position={[-2.537, -0.478, -0.321]}
          rotation={[0, 0.591, 0]}
          scale={0.818}
        />
        <mesh
          geometry={nodes.StaticMeshActor_46_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[-2.488, -0.634, 0.039]}
          rotation={[0, 0.96, 0]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_47_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[-2.449, -0.63, 0.061]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_48_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[-2.523, -0.63, 0.008]}
          rotation={[0, -1.571, 0]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_49_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_white__0}
          position={[-2.453, -0.552, -0.046]}
          rotation={[-Math.PI, -0.96, -Math.PI]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_50_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_white__0}
          position={[-1.822, -0.452, 0.396]}
          rotation={[0, 0.96, 0]}
        />
        <group
          position={[-1.851, -0.475, 0.377]}
          rotation={[Math.PI / 2, 0, 2.182]}
        >
          <mesh
            geometry={nodes.Cylinder025.geometry}
            material={materials.Plastic_Simple_Blurry_white__0}
          />
          <mesh
            geometry={nodes.Cylinder025_1.geometry}
            material={materials.Plastic_Simple_Blurry_Black__0}
          />
        </group>
        <mesh
          geometry={nodes.StaticMeshActor_52_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[-1.82, -0.474, 0.452]}
          rotation={[Math.PI / 2, 0, -0.858]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_53_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[-2.481, -0.435, -0.063]}
          rotation={[Math.PI / 2, 0, 2.182]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_54_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[-2.294, -0.634, 0.125]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_55_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[-2.316, -0.611, 0.084]}
          rotation={[Math.PI / 2, 0, 1.134]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_56_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_red__0}
          position={[-2.312, -0.611, 0.082]}
          rotation={[Math.PI / 2, 0, 1.134]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_57_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[-2.38, -0.589, 0.141]}
          rotation={[1.516, 0.18, -1.272]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_58_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[-2.283, -0.634, 0.111]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_59_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[-2.274, -0.572, 0.001]}
          rotation={[1.142, 0.536, -0.84]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_61_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_white__0}
          position={[0.309, -0.906, 0]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_62_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[0.151, -0.627, 0.15]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_63_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[0.151, -0.627, -0.15]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={-1}
        />
        <mesh
          geometry={nodes.StaticMeshActor_64_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[0.156, -0.71, -0.001]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_65_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[0.156, -0.725, -0.005]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_66_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[0.307, -0.779, 0.22]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_69_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[0.307, -0.779, -0.22]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={-1}
        />
        <mesh
          geometry={nodes.StaticMeshActor_67_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[0.365, -0.89, 0.22]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_68_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[0.365, -0.89, -0.22]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={-1}
        />
        <mesh
          geometry={nodes.StaticMeshActor_70_StaticMeshComponent0.geometry}
          material={materials.Leather_white_16_50cm__0}
          position={[0.466, -0.436, 0]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={1.135}
        />
        <mesh
          geometry={nodes.StaticMeshActor_133_StaticMeshComponent0.geometry}
          material={materials.Leather_white_16_50cm__0}
          position={[2.152, 1.054, 0]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[1.135, 1.135, 0.77]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_71_StaticMeshComponent0.geometry}
          material={materials.Leather_black_16_50cm__0}
          position={[0.466, -0.436, 0]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={1.135}
        />
        <mesh
          geometry={nodes.StaticMeshActor_134_StaticMeshComponent0.geometry}
          material={materials.Leather_black_16_50cm__0}
          position={[2.152, 1.054, 0]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[1.135, 1.135, 0.77]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_72_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[0.618, -0.693, 0.17]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_73_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[0.685, -0.697, 0.171]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.973}
        />
        <mesh
          geometry={nodes.StaticMeshActor_74_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[0.505, -0.375, 0.082]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_75_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[0.518, -0.376, -0.093]}
          rotation={[0, -0.087, 0]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_76_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[0.518, -0.376, -0.093]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_77_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[0.518, -0.33, -0.093]}
          rotation={[0, -0.087, 0]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_78_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[0.518, -0.328, -0.093]}
          rotation={[0, -0.087, 0]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_79_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[0.512, -0.278, -0.031]}
          rotation={[Math.PI / 2, 0, 0.087]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_80_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[0.523, -0.278, -0.155]}
          rotation={[Math.PI / 2, 0, -3.054]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_82_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[0.545, -0.232, -0.142]}
          rotation={[1.547, 0.26, -1.477]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_83_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[0.55, -0.246, -0.149]}
          rotation={[1.547, 0.26, -1.477]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_84_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[0.554, -0.261, -0.149]}
          rotation={[1.547, 0.26, -1.477]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_85_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[0.556, -0.267, -0.149]}
          rotation={[1.547, 0.26, -1.477]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_86_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[0.557, -0.274, -0.149]}
          rotation={[1.547, 0.26, -1.477]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_87_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[0.559, -0.28, -0.149]}
          rotation={[1.547, 0.26, -1.477]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_88_StaticMeshComponent0.geometry}
          material={materials.Plastic_Metallic_Black__0}
          position={[0.608, -0.398, -0.135]}
          rotation={[0, 0, -0.677]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_89_StaticMeshComponent0.geometry}
          material={materials.Object_671c6131_88fb_4726_94f4_527a1b1d9789}
          position={[0.608, -0.398, -0.135]}
          rotation={[0, 0, -0.677]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_90_StaticMeshComponent0.geometry}
          material={materials.Glass_Window_Neutral__0}
          position={[0.608, -0.398, -0.135]}
          rotation={[0, 0, -0.677]}
        />
        <group position={[0.694, -0.467, -0.129]} rotation={[0, 0, -0.678]}>
          <mesh
            geometry={nodes.Box039.geometry}
            material={materials.Plastic_Simple_Blurry_Black__0}
          />
          <mesh
            geometry={nodes.Box039_1.geometry}
            material={materials.Aluminum_Blurry__0}
          />
        </group>
        <group
          position={[0.711, -0.447, -0.104]}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <mesh
            geometry={nodes.Cylinder037.geometry}
            material={materials.Aluminum_Blurry__0}
          />
          <mesh
            geometry={nodes.Cylinder037_1.geometry}
            material={materials.Plastic_Simple_Blurry_Black__0}
          />
        </group>
        <mesh
          geometry={nodes.StaticMeshActor_93_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[0.756, -0.517, 0.036]}
          rotation={[0, 0, -0.676]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_94_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[0.74, -0.502, 0.155]}
          rotation={[0, 0, -0.684]}
          scale={[1.6, 0.717, 1.6]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_95_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[0.774, -0.53, 0.155]}
          rotation={[0, 0, -0.684]}
          scale={[1.6, 0.717, 1.6]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_96_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[0.74, -0.502, 0.038]}
          rotation={[0, 0, -0.684]}
          scale={[1.6, 0.717, 1.6]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_97_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[0.774, -0.53, 0.038]}
          rotation={[0, 0, -0.684]}
          scale={[1.6, 0.717, 1.6]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_98_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[0.74, -0.502, -0.082]}
          rotation={[0, 0, -0.684]}
          scale={[1.6, 0.717, 1.6]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_99_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[0.774, -0.53, -0.082]}
          rotation={[0, 0, -0.684]}
          scale={[1.6, 0.717, 1.6]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_100_StaticMeshComponent0.geometry}
          material={materials.Plastic_Metallic_Black__0}
          position={[0.764, -0.521, 0.131]}
          rotation={[0, 0, -0.677]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_101_StaticMeshComponent0.geometry}
          material={materials.Plastic_Metallic_Black__0}
          position={[0.764, -0.521, 0.109]}
          rotation={[0, 0, -0.677]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_102_StaticMeshComponent0.geometry}
          material={materials.Plastic_Metallic_Black__0}
          position={[0.764, -0.521, 0.087]}
          rotation={[0, 0, -0.677]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_103_StaticMeshComponent0.geometry}
          material={materials.Plastic_Metallic_Black__0}
          position={[0.764, -0.521, 0.065]}
          rotation={[0, 0, -0.677]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_104_StaticMeshComponent0.geometry}
          material={materials.Plastic_Metallic_Black__0}
          position={[0.764, -0.521, 0.042]}
          rotation={[0, 0, -0.677]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_105_StaticMeshComponent0.geometry}
          material={materials.Plastic_Metallic_Black__0}
          position={[0.764, -0.521, 0.02]}
          rotation={[0, 0, -0.677]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_106_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_white__0}
          position={[0.752, -0.511, 0.131]}
          rotation={[Math.PI / 2, 0.895, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_107_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_white__0}
          position={[0.753, -0.513, 0.11]}
          rotation={[Math.PI / 2, 0.895, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_108_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_white__0}
          position={[0.752, -0.511, 0.087]}
          rotation={[Math.PI / 2, 0.895, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_109_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_white__0}
          position={[0.752, -0.511, 0.064]}
          rotation={[Math.PI / 2, 0.895, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_110_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_white__0}
          position={[0.753, -0.513, 0.042]}
          rotation={[Math.PI / 2, 0.895, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_111_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_white__0}
          position={[0.753, -0.513, 0.021]}
          rotation={[Math.PI / 2, 0.895, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_112_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_white__0}
          position={[0.757, -0.515, -0.037]}
          rotation={[-Math.PI / 2, 0.676, Math.PI / 2]}
          scale={[0.003, 0.003, 0]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_113_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[0.786, -0.591, -0.14]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_114_StaticMeshComponent0.geometry}
          material={materials.Plastic_Metallic_Black__0}
          position={[0.788, -0.573, -0.14]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_115_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[0.788, -0.608, -0.14]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_116_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[0.789, -0.66, 0.022]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_117_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[0.717, -0.716, -0.176]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_119_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[0.628, -0.716, -0.176]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_121_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[0.539, -0.716, -0.176]}
        />
        <group position={[0.717, -0.776, -0.199]}>
          <mesh
            geometry={nodes.Cylinder046.geometry}
            material={materials.Aluminum_Blurry__0}
          />
          <mesh
            geometry={nodes.Cylinder046_1.geometry}
            material={materials.Plastic_Simple_Blurry_Black__0}
          />
        </group>
        <group position={[0.628, -0.776, -0.199]}>
          <mesh
            geometry={nodes.Cylinder047.geometry}
            material={materials.Aluminum_Blurry__0}
          />
          <mesh
            geometry={nodes.Cylinder047_1.geometry}
            material={materials.Plastic_Simple_Blurry_Black__0}
          />
        </group>
        <group position={[0.539, -0.776, -0.199]}>
          <mesh
            geometry={nodes.Cylinder048.geometry}
            material={materials.Aluminum_Blurry__0}
          />
          <mesh
            geometry={nodes.Cylinder048_1.geometry}
            material={materials.Plastic_Simple_Blurry_Black__0}
          />
        </group>
        <mesh
          geometry={nodes.StaticMeshActor_123_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[0.691, -0.466, 0.089]}
          rotation={[0, 0, -0.676]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_124_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[0.746, -0.397, 0.089]}
          rotation={[0, 0, -0.676]}
          scale={0.747}
        />
        <mesh
          geometry={nodes.StaticMeshActor_125_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[0.745, -0.398, 0.089]}
          rotation={[0, 0, -0.676]}
          scale={0.747}
        />
        <mesh
          geometry={nodes.StaticMeshActor_126_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[0.737, -0.409, 0.089]}
          rotation={[0, 0, -0.676]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_127_StaticMeshComponent0.geometry}
          material={materials.Leather_white_16_50cm__0}
          position={[1.225, -0.642, 0]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_128_StaticMeshComponent0.geometry}
          material={materials.Leather_black_16_50cm__0}
          position={[1.225, -0.642, 0]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_129_StaticMeshComponent0.geometry}
          material={materials.Leather_black_16_50cm__0}
          position={[1.225, -0.584, 0]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_130_StaticMeshComponent0.geometry}
          material={materials.Object_f38cbb3f_7b27_4da8_bd73_27678236849c}
          position={[1.951, 0.174, 0]}
          scale={[0.88, 1, 1]}
        />
        <mesh
          name='Poling Platform'
          ref={secFencRef}
          material-color={colors["Poling Platform"]}
          geometry={nodes.StaticMeshActor_131_StaticMeshComponent0.geometry}
          material={materials.Metal}
          position={[1.793, -0.234, 0.447]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name='Poling Platform'
          ref={secFencRef}
          material-color={colors["Poling Platform"]}
          geometry={nodes.StaticMeshActor_132_StaticMeshComponent0.geometry}
          material={materials.Metal}
          position={[2.174, 1.097, 0.015]}
        />
        <mesh
          name='Poling Platform'
          ref={secFencRef}
          material-color={colors["Poling Platform"]}
          geometry={nodes.StaticMeshActor_135_StaticMeshComponent0.geometry}
          material={materials.Metal}
          position={[2.175, 0.676, 0.036]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_137_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[1.747, -0.634, 0.437]}
          rotation={[0, -1.571, 0]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_138_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[1.947, -0.634, 0.579]}
          rotation={[0, -1.571, 0]}
          scale={[1, 1, 0.746]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_139_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[1.747, -0.634, -0.437]}
          rotation={[-Math.PI, 1.571, 0]}
          scale={-1}
        />
        <mesh
          geometry={nodes.StaticMeshActor_140_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[1.947, -0.634, -0.579]}
          rotation={[-Math.PI, 1.571, 0]}
          scale={[-1, -1, -0.746]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_141_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[1.992, -0.634, -0.685]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_142_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[1.992, -0.634, 0.685]}
          rotation={[0, 0, Math.PI]}
          scale={-1}
        />
        <mesh
          geometry={nodes.StaticMeshActor_143_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[-2.074, -0.639, 0]}
          rotation={[0, 0, Math.PI]}
          scale={-1}
        />
        <mesh
          geometry={nodes.StaticMeshActor_144_StaticMeshComponent0.geometry}
          material={materials.Plastic_Metallic_Black__0}
          position={[0.284, -0.612, -0.741]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_145_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[2.111, -0.634, -0.759]}
          rotation={[-0.001, 0, 0]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_146_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[-0.891, -0.634, -0.76]}
          rotation={[-0.001, 0, 0]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_147_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[0.454, -0.634, -0.722]}
          rotation={[-0.001, 0, 0]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_148_StaticMeshComponent0.geometry}
          material={materials.Plastic_Metallic_Black__0}
          position={[-2.165, -0.621, -0.729]}
          rotation={[0.436, 0, 0]}
        />
        <group
          position={[1.138, -0.757, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[-1.015, -1, -0.822]}
        >
          <mesh
            geometry={nodes.Object003.geometry}
            material={materials.Plastic_Simple_Blurry_white__0}
          />
          <mesh
            geometry={nodes.Object003_1.geometry}
            material={materials.Plastic_Simple_Blurry_Black__0}
          />
        </group>
        <mesh
          geometry={nodes.StaticMeshActor_150_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_white__1}
          position={[2.116, -0.728, 0.537]}
          rotation={[1.571, -0.488, -1.571]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_166_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_white__1}
          position={[2.116, -0.728, -0.537]}
          rotation={[-1.571, 0.488, 1.571]}
          scale={-1}
        />
        <mesh
          geometry={nodes.StaticMeshActor_151_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[2.141, -0.691, 0.492]}
          rotation={[1.571, -0.488, -1.571]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_152_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[2.141, -0.691, 0.581]}
          rotation={[1.571, -0.488, -1.571]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_153_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[2.099, -0.77, 0.492]}
          rotation={[1.571, -0.488, -1.571]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_154_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[2.099, -0.77, 0.581]}
          rotation={[1.571, -0.488, -1.571]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_170_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[2.141, -0.691, -0.492]}
          rotation={[-1.571, 0.488, 1.571]}
          scale={-1}
        />
        <mesh
          geometry={nodes.StaticMeshActor_171_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[2.141, -0.691, -0.581]}
          rotation={[-1.571, 0.488, 1.571]}
          scale={-1}
        />
        <mesh
          geometry={nodes.StaticMeshActor_172_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[2.099, -0.77, -0.492]}
          rotation={[-1.571, 0.488, 1.571]}
          scale={-1}
        />
        <mesh
          geometry={nodes.StaticMeshActor_173_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[2.099, -0.77, -0.581]}
          rotation={[-1.571, 0.488, 1.571]}
          scale={-1}
        />
        <mesh
          name='Power Pole'
          ref={secFencRef}
          material-color={colors["Power Pole"]}
          geometry={nodes.StaticMeshActor_155_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_white__1}
          position={[2.219, -0.712, 0.539]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.803, 1, 1]}
        />
        <mesh
          name='Power Pole'
          ref={secFencRef}
          material-color={colors["Power Pole"]}
          geometry={nodes.StaticMeshActor_179_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_white__1}
          position={[2.219, -0.712, -0.539]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[-0.803, -1, -1]}
        />
        <mesh
          name='Power Pole'
          ref={secFencRef}
          material-color={colors["Power Pole"]}
          geometry={nodes.StaticMeshActor_156_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_white__1}
          position={[2.327, -0.792, 0.539]}
        />
        <mesh
          name='Power Pole'
          ref={secFencRef}
          material-color={colors["Power Pole"]}
          geometry={nodes.StaticMeshActor_167_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_white__1}
          position={[2.327, -0.792, -0.539]}
          rotation={[0, 0, -Math.PI]}
          scale={-1}
        />
        <mesh
          name='Power Pole'
          ref={secFencRef}
          material-color={colors["Power Pole"]}
          geometry={nodes.StaticMeshActor_157_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_white__1}
          position={[2.288, -0.716, 0.539]}
        />
        <mesh
          name='Power Pole'
          ref={secFencRef}
          material-color={colors["Power Pole"]}
          geometry={nodes.StaticMeshActor_168_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_white__1}
          position={[2.288, -0.716, -0.539]}
          rotation={[0, 0, -Math.PI]}
          scale={-1}
        />
        <mesh
          name='Power Pole'
          ref={secFencRef}
          material-color={colors["Power Pole"]}
          geometry={nodes.StaticMeshActor_158_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_white__1}
          position={[2.321, 0.082, 0.522]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[1.136, 1, 1]}
        />
        <mesh
          name='Power Pole'
          ref={secFencRef}
          material-color={colors["Power Pole"]}
          geometry={nodes.StaticMeshActor_169_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_white__1}
          position={[2.321, 0.082, -0.522]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[-1.136, -1, -1]}
        />
        <mesh
          name='Power Pole'
          ref={secFencRef}
          material-color={colors["Power Pole"]}
          geometry={nodes.StaticMeshActor_159_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_white__1}
          position={[2.312, 0.116, 0.523]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name='Power Pole'
          ref={secFencRef}
          material-color={colors["Power Pole"]}
          geometry={nodes.StaticMeshActor_174_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_white__1}
          position={[2.312, 0.116, -0.523]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={-1}
        />
        <group position={[2.364, -0.775, 0.539]}>
          <mesh
            name='Power Poles'
            ref={secFencRef}
            material-color={colors["Power Poles"]}
            geometry={nodes.Cylinder063.geometry}
            material={materials.Plastic_Simple_Blurry_white__1}
          />
          <mesh
            geometry={nodes.Cylinder063_1.geometry}
            material={materials.Plastic_Simple_Blurry_Black__0}
          />
        </group>
        <mesh
          geometry={nodes.StaticMeshActor_161_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[2.112, -0.665, 0.315]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_180_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[2.112, -0.665, -0.315]}
          rotation={[0, 0, -Math.PI]}
          scale={-1}
        />
        <mesh
          geometry={nodes.StaticMeshActor_162_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[2.112, -0.679, 0.315]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_181_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[2.112, -0.679, -0.315]}
          rotation={[0, 0, -Math.PI]}
          scale={-1}
        />
        <mesh
          geometry={nodes.StaticMeshActor_163_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[2.279, -0.665, 0.54]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_164_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[2.279, -0.679, 0.54]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_176_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[2.279, -0.665, -0.54]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={-1}
        />
        <mesh
          geometry={nodes.StaticMeshActor_177_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[2.279, -0.679, -0.54]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={-1}
        />
        <mesh
          geometry={nodes.StaticMeshActor_165_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[2.031, -0.639, 0.211]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_178_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[2.031, -0.639, -0.211]}
          rotation={[0, 0, -Math.PI]}
          scale={-1}
        />
        <group
          position={[2.364, -0.775, -0.539]}
          rotation={[0, 0, -Math.PI]}
          scale={-1}
        >
          <mesh
            geometry={nodes.Cylinder072.geometry}
            material={materials.Plastic_Simple_Blurry_white__1}
          />
          <mesh
            geometry={nodes.Cylinder072_1.geometry}
            material={materials.Plastic_Simple_Blurry_Black__0}
          />
        </group>
        <mesh
          geometry={nodes.StaticMeshActor_182_StaticMeshComponent0.geometry}
          material={materials.Metal_Weathered_S01_20cm__0}
          position={[2.064, -0.604, 0]}
          rotation={[0, 0, -0.436]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_183_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[2.073, -0.579, -0.165]}
          rotation={[Math.PI / 2, -0.436, Math.PI / 2]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_184_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[2.073, -0.579, 0.165]}
          rotation={[-Math.PI / 2, 0.436, -Math.PI / 2]}
          scale={-1}
        />
        <mesh
          geometry={nodes.StaticMeshActor_185_StaticMeshComponent0.geometry}
          material={materials.Plastic_Metallic_white_0}
          position={[2.319, -0.639, -0.019]}
          rotation={[0, -1.571, 0]}
          scale={0.005}
        />
        <mesh
          geometry={nodes.StaticMeshActor_186_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[2.319, -0.639, -0.019]}
          rotation={[0, -1.571, 0]}
          scale={0.005}
        />
        <group
          position={[2.319, -0.639, -0.019]}
          rotation={[0, -1.571, 0]}
          scale={0.005}
        >
          <mesh
            geometry={nodes["002_LOW_0"].geometry}
            material={materials.Plastic_Metallic_white_0}
          />
          <mesh
            geometry={nodes["002_LOW_0_1"].geometry}
            material={materials.Plastic_Metallic_Black__0}
          />
        </group>
        <mesh
          geometry={nodes.StaticMeshActor_188_StaticMeshComponent0.geometry}
          material={materials.Plastic_Metallic_white_0}
          position={[2.319, -0.639, -0.019]}
          rotation={[0, -1.571, 0]}
          scale={0.005}
        />
        <mesh
          geometry={nodes.StaticMeshActor_189_StaticMeshComponent0.geometry}
          material={materials.Plastic_Metallic_white_0}
          position={[2.319, -0.639, -0.019]}
          rotation={[0, -1.571, 0]}
          scale={0.005}
        />
        <mesh
          geometry={nodes.StaticMeshActor_190_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[2.319, -0.639, -0.019]}
          rotation={[0, -1.571, 0]}
          scale={0.005}
        />
        <mesh
          geometry={nodes.StaticMeshActor_191_StaticMeshComponent0.geometry}
          material={materials.Aluminum_Blurry__0}
          position={[2.319, -0.639, -0.019]}
          rotation={[0, -1.571, 0]}
          scale={0.005}
        />
        <mesh
          geometry={nodes.StaticMeshActor_192_StaticMeshComponent0.geometry}
          material={materials.Plastic_Metallic_white_0}
          position={[2.271, -0.462, -0.095]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_193_StaticMeshComponent0.geometry}
          material={materials.Plastic_Metallic_white_0}
          position={[2.271, -0.457, 0.068]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_194_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[1.955, -0.461, -0.183]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_195_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[1.856, -0.634, -0.271]}
        />
        <mesh
          geometry={nodes.StaticMeshActor_196_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__0}
          position={[1.94, -0.462, -0.135]}
        />
        <group
          position={[1.822, -0.664, -0.038]}
          rotation={[0, Math.PI / 2, 0]}
        >
          <mesh
            geometry={nodes.Shape018.geometry}
            material={materials.Plastic_Simple_Blurry_Black__0}
          />
          <mesh
            geometry={nodes.Shape018_1.geometry}
            material={materials.Object_f38cbb3f_7b27_4da8_bd73_27678236849c}
          />
        </group>
        <group
          position={[0.556, -0.312, -0.089]}
          rotation={[0.023, -0.084, 0.263]}
          scale={[1, 1, 0.972]}
        >
          <mesh
            geometry={nodes.Box038.geometry}
            material={materials.Plastic_Simple_Blurry_Black__0}
          />
          <mesh
            geometry={nodes.Box038_1.geometry}
            material={materials.Object_2390314d_9d4d_4dbb_b139_60ab16757409}
          />
        </group>
        <mesh
          geometry={nodes.StaticMeshActor_213_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__1}
          position={[1.783, -0.776, -0.735]}
          rotation={[0, 1.557, -1.909]}
          scale={0.012}
        />
        <mesh
          geometry={nodes.StaticMeshActor_214_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__1}
          position={[-0.781, -0.761, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={0.013}
        />
        <mesh
          geometry={nodes.StaticMeshActor_215_StaticMeshComponent0.geometry}
          material={materials.Glass_Bumpy_01_10cm__0}
          position={[1.498, -0.64, 0]}
          rotation={[-Math.PI, 0, Math.PI]}
          scale={0.01}
        />
        <mesh
          geometry={nodes.StaticMeshActor_216_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__1}
          position={[1.783, -0.779, 0.734]}
          rotation={[0, -1.554, -1.909]}
          scale={0.013}
        />
        <mesh
          geometry={nodes.StaticMeshActor_217_StaticMeshComponent0.geometry}
          material={materials.Plastic_Simple_Blurry_Black__1}
          position={[1.962, 0.175, 0]}
          rotation={[-Math.PI, 0, Math.PI]}
          scale={[0.014, 0.003, 0.014]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/skimmerskiffsixteen.glb");
