/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.8 public/models/skimmer-skiff-fourteen.glb --keepmeshes
*/

import React, { useEffect, useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import gsap from "gsap";
import { useThree } from "@react-three/fiber";
import useColorStore from "../Utils/store";

export function Model(props) {
  const { nodes, materials } = useGLTF('./models/skimmer-skiff-fourteen.glb')
  const { colors, activeState, setActiveState } = useColorStore();
   const { camera } = useThree();
   const primFencRef = useRef();
   const secFencRef = useRef();

    useEffect(() => {
     switch (activeState) {
       case 0:
         gsap.to(camera.position, {
           x: 1,
           y: 1.5,
           z: 3.5,
           duration: 2,
           ease: "power.easeOut",
           onComplete: () => {
             setTimeout(() => {}, 100);
           },
           onStart: () => {
             gsap.to(camera.rotation, {
               x: 1,
           y: 1.5,
           z: 3.5,
             });
           },
        });
         break;
    
     
       case "Hull Color":
         gsap.to(camera.position, {
           x: 1,
           y: 0,
           z: 2.5,
           duration: 3,
           ease: "power.easeOut",

           onUpdate: () => {
             camera.lookAt(...primFencRef.current.position);
           },
         });
         break;

         case "Power Pole":
          gsap.to(camera.position, {
            x: 2,
            y: 3,
            z: 3.5,
            duration: 3,
            ease: "power.easeOut",

            onUpdate: () => {
              camera.lookAt(...primFencRef.current.position);
            },
          });
          break;
          case "Poling Platform":
          gsap.to(camera.position, {
            x: 2,
            y: 3,
            z: 3.5,
            duration: 3,
            ease: "power.easeOut",

            onUpdate: () => {
              camera.lookAt(...primFencRef.current.position);
            },
          });
          break;
     
     }
   }, [activeState]);



  return (
    <group {...props} dispose={null}>
      <group position={[0.003, 0.600, -0.001]}>
        <group position={[-2.248, -0.072, 0.065]} scale={[1, 1, 0.881]} >
          <mesh geometry={nodes.StaticMeshActor_8_StaticMeshComponent0.geometry} material={materials.Plastic_Metallic_Black__0} position={[-0.288, 0.025, -0.394]} rotation={[0, 0.591, 0]} scale={0.818} />
          <mesh geometry={nodes.StaticMeshActor_9_StaticMeshComponent0.geometry} material={materials.Aluminum_Blurry__0} position={[0.428, 0.029, 0.379]} rotation={[Math.PI / 2, 0, -0.858]} scale={[0.881, 1, 1.135]} />
          <mesh geometry={nodes.StaticMeshActor_10_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_white__0} position={[-0.205, -0.049, -0.119]} rotation={[-Math.PI, -0.96, -Math.PI]} scale={[0.881, 1, 1.135]} />
          <group position={[-0.279, 0.029, -0.405]} rotation={[1.555, -0.011, 0.611]} scale={[1, 0.881, 1.135]}>
            <mesh geometry={nodes.Cylinder019.geometry} material={materials.Plastic_Metallic_Black__0} />
            <mesh geometry={nodes.Cylinder019_1.geometry} material={materials.Plastic_Simple_Blurry_white__0} />
          </group>
          <mesh geometry={nodes.StaticMeshActor_12_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[-0.354, -0.024, -0.292]} rotation={[0, -0.6, 0]} scale={[0.967, 1, 0.707]} />
          <mesh geometry={nodes.StaticMeshActor_13_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[-0.417, -0.024, -0.202]} rotation={[0, -0.6, 0]} scale={[0.967, 1, 0.707]} />
          <mesh geometry={nodes.StaticMeshActor_14_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[-0.232, 0.067, -0.2]} rotation={[Math.PI / 2, 0, 2.182]} scale={[0.881, 1, 1.135]} />
          <mesh geometry={nodes.StaticMeshActor_15_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_white__0} position={[0.426, 0.051, 0.323]} rotation={[0, 0.96, 0]} scale={[0.881, 1, 1.135]} />
          <group position={[0.397, 0.028, 0.304]} rotation={[Math.PI / 2, 0, 2.182]} scale={[0.881, 1, 1.135]}>
            <mesh geometry={nodes.Cylinder025.geometry} material={materials.Plastic_Simple_Blurry_white__0} />
            <mesh geometry={nodes.Cylinder025_1.geometry} material={materials.Plastic_Simple_Blurry_Black__0} />
          </group>
          <group position={[-0.345, -0.113, -0.288]} rotation={[0, -0.611, 0]}>
            <mesh geometry={nodes.Box013.geometry} material={materials.Plastic_Simple_Blurry_Black__0} />
            <mesh geometry={nodes.Box013_1.geometry} material={materials.Plastic_Simple_Blurry_white__0} />
          </group>
          <mesh geometry={nodes.StaticMeshActor_18_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_white__0} position={[-0.173, -0.113, -0.098]} rotation={[0, -0.611, 0]} />
          <mesh geometry={nodes.StaticMeshActor_19_StaticMeshComponent0.geometry} material={materials.Aluminum_Blurry__0} position={[-0.318, -0.083, -0.247]} rotation={[Math.PI / 2, 0, 0.611]} scale={[1, 0.881, 1.135]} />
          <mesh geometry={nodes.StaticMeshActor_20_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[-0.068, -0.108, 0.01]} rotation={[Math.PI / 2, 0, 1.134]} scale={[0.881, 1, 1.135]} />
          <mesh geometry={nodes.StaticMeshActor_21_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_red__0} position={[-0.064, -0.108, 0.009]} rotation={[Math.PI / 2, 0, 1.134]} scale={[0.881, 1, 1.135]} />
          <mesh geometry={nodes.StaticMeshActor_22_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[-0.132, -0.086, 0.068]} rotation={[1.516, 0.18, -1.272]} scale={[0.881, 1, 1.135]} />
          <mesh geometry={nodes.StaticMeshActor_23_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[-0.026, -0.069, -0.072]} rotation={[1.142, 0.536, -0.84]} scale={[0.881, 1, 1.135]} />
          <mesh geometry={nodes.StaticMeshActor_24_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[-0.24, -0.131, -0.034]} rotation={[0, 0.96, 0]} scale={[0.881, 1, 1.135]} />
          <mesh geometry={nodes.StaticMeshActor_25_StaticMeshComponent0.geometry} material={materials.Aluminum_Blurry__0} position={[-0.201, -0.127, -0.012]} />
          <mesh geometry={nodes.StaticMeshActor_26_StaticMeshComponent0.geometry} material={materials.Aluminum_Blurry__0} position={[-0.274, -0.127, -0.066]} rotation={[0, -1.571, 0]} scale={[0.881, 1, 1.135]} />
          <mesh geometry={nodes.StaticMeshActor_27_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[-0.046, -0.131, 0.051]} />
          <mesh geometry={nodes.StaticMeshActor_28_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_white__0} position={[-0.183, -0.138, -0.104]} rotation={[0, -0.611, 0]} />
          <mesh geometry={nodes.StaticMeshActor_29_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[-0.034, -0.131, 0.038]} />
        </group>
        <group position={[0.878, -0.18, 0.001]} scale={[1, 1, 0.881]} >
          <mesh geometry={nodes.StaticMeshActor_49_StaticMeshComponent0.geometry} material={materials.Leather_white_16_50cm__0} position={[0, -0.031, 0]} />
          <mesh geometry={nodes.StaticMeshActor_50_StaticMeshComponent0.geometry} material={materials.Leather_black_16_50cm__0} position={[0, 0.026, 0]} />
          <mesh geometry={nodes.StaticMeshActor_51_StaticMeshComponent0.geometry} material={materials.Leather_black_16_50cm__0} position={[0, -0.031, 0]} />
        </group>
        <group position={[-0.054, -0.317, 0.001]} scale={[1, 1, 0.881]} >
          <mesh geometry={nodes.StaticMeshActor_100_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_white__0} position={[0.002, -0.158, 0]} />
          <mesh geometry={nodes.StaticMeshActor_101_StaticMeshComponent0.geometry} material={materials.Aluminum_Blurry__0} position={[-0.151, 0.023, -0.005]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.881, 1, 1.135]} />
          <mesh geometry={nodes.StaticMeshActor_102_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[-0.15, 0.038, -0.001]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.881, 1, 1.135]} />
          <mesh geometry={nodes.StaticMeshActor_103_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[-0.156, 0.121, -0.15]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.881, -1, -1.135]} />
          <mesh geometry={nodes.StaticMeshActor_104_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[-0.156, 0.121, 0.15]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.881, 1, 1.135]} />
          <mesh geometry={nodes.StaticMeshActor_105_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[0, -0.032, -0.22]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[-1, -0.881, -1.135]} />
          <mesh geometry={nodes.StaticMeshActor_106_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[0.058, -0.142, -0.22]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.881, -1, -1.135]} />
          <mesh geometry={nodes.StaticMeshActor_107_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[0.058, -0.142, 0.22]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.881, 1, 1.135]} />
          <mesh geometry={nodes.StaticMeshActor_108_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[0, -0.032, 0.22]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 0.881, 1.135]} />
        </group>
        <group position={[0.157, 0.133, 0.002]} >
          <mesh geometry={nodes.StaticMeshActor_132_StaticMeshComponent0.geometry} material={materials.Aluminum_Blurry__0} position={[-0.013, -0.078, 0]} rotation={[0, 0.087, 0]} scale={[1, 1, 0.881]} />
          <mesh geometry={nodes.StaticMeshActor_133_StaticMeshComponent0.geometry} material={materials.Aluminum_Blurry__0} position={[-0.013, -0.079, 0]} scale={[1, 1, 0.881]} />
          <mesh geometry={nodes.StaticMeshActor_134_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[-0.013, -0.031, 0]} scale={[1, 1, 0.881]} />
          <mesh geometry={nodes.StaticMeshActor_135_StaticMeshComponent0.geometry} material={materials.Aluminum_Blurry__0} position={[-0.013, -0.032, 0]} scale={[1, 1, 0.881]} />
          <group position={[0.026, -0.014, 0]} rotation={[0.023, 0.003, 0.261]} scale={[1, 1, 0.856]}>
            <mesh geometry={nodes.Box038.geometry} material={materials.Plastic_Simple_Blurry_Black__0_2} />
            <mesh geometry={nodes.Box038_1.geometry} material={materials.Object_647876b5_6fd7_431e_a0f6_00a1ad3df2f5} />
            <mesh geometry={nodes.Box038_2.geometry} material={materials.Plastic_Simple_Blurry_Black__01} />
          </group>
          <mesh geometry={nodes.StaticMeshActor_137_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[-0.013, 0.019, -0.055]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[1, 0.881, 1]} />
          <mesh geometry={nodes.StaticMeshActor_138_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[0.01, 0.066, -0.046]} rotation={[1.57, 0.261, -1.568]} scale={[0.881, 1, 1]} />
          <mesh geometry={nodes.StaticMeshActor_139_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[0.014, 0.051, -0.052]} rotation={[1.57, 0.261, -1.568]} scale={[0.881, 1, 1]} />
          <mesh geometry={nodes.StaticMeshActor_140_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[0.018, 0.037, -0.052]} rotation={[1.57, 0.261, -1.568]} scale={[0.881, 1, 1]} />
          <mesh geometry={nodes.StaticMeshActor_141_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[0.02, 0.03, -0.052]} rotation={[1.57, 0.261, -1.568]} scale={[0.881, 1, 1]} />
          <mesh geometry={nodes.StaticMeshActor_142_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[0.022, 0.024, -0.052]} rotation={[1.57, 0.261, -1.568]} scale={[0.881, 1, 1]} />
          <mesh geometry={nodes.StaticMeshActor_143_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[0.024, 0.017, -0.052]} rotation={[1.57, 0.261, -1.568]} scale={[0.881, 1, 1]} />
          <mesh geometry={nodes.StaticMeshActor_144_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[-0.013, 0.019, 0.054]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 0.881, 1]} />
        </group>
        <mesh geometry={nodes.StaticMeshActor_0_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_white__01} position={[-0.084, -0.357, 0.001]}  />
        <mesh geometry={nodes.StaticMeshActor_1_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_white__01} position={[1.217, -0.137, 0.454]}  />
        <mesh geometry={nodes.StaticMeshActor_2_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__01} position={[1.754, -0.234, 0.19]}  />
        <mesh name='Hull Color'
        ref={primFencRef}
        material-color={colors["Hull Color"]} geometry={nodes.StaticMeshActor_3_StaticMeshComponent0.geometry} material={materials.Carpaint_Simple_Dahlia_Yellow__0} position={[-0.007, -0.235, 0.001]} />
        <mesh geometry={nodes.StaticMeshActor_4_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__01} position={[-0.007, -0.248, 0.001]}  />
        <mesh geometry={nodes.StaticMeshActor_5_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__01} position={[-0.007, -0.246, 0.001]}  />
        <mesh geometry={nodes.StaticMeshActor_6_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_white__01} position={[1.217, -0.137, -0.453]}  />
        <mesh geometry={nodes.StaticMeshActor_7_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__01} position={[1.754, -0.234, -0.188]} />
        <mesh geometry={nodes.StaticMeshActor_30_StaticMeshComponent0.geometry} material={materials.Aluminum_Blurry__0} position={[-1.995, -0.29, 0.365]} />
        <group position={[-1.154, -0.208, 0.001]}>
          <mesh geometry={nodes.Cylinder014.geometry} material={materials.Plastic_Simple_Blurry_Black__0}  />
          <mesh geometry={nodes.Cylinder014_1.geometry} material={materials.Aluminum_Blurry__0}  />
        </group>
        <mesh geometry={nodes.StaticMeshActor_32_StaticMeshComponent0.geometry} material={materials.Aluminum_Blurry__0} position={[-1.998, -0.208, 0.001]}  />
        <mesh geometry={nodes.StaticMeshActor_33_StaticMeshComponent0.geometry} material={materials.Plastic_Metallic_Black__0} position={[1.236, -0.358, 0.655]}  />
        <mesh geometry={nodes.StaticMeshActor_34_StaticMeshComponent0.geometry} material={materials.Plastic_Metallic_Black__0} position={[1.236, -0.358, -0.653]} />
        <mesh geometry={nodes.StaticMeshActor_35_StaticMeshComponent0.geometry} material={materials.Aluminum_Blurry__0} position={[-1.75, -0.208, 0.142]} />
        <mesh geometry={nodes.StaticMeshActor_36_StaticMeshComponent0.geometry} material={materials.Aluminum_Blurry__0} position={[1.133, -0.208, 0.549]} />
        <mesh geometry={nodes.StaticMeshActor_37_StaticMeshComponent0.geometry} material={materials.Aluminum_Blurry__0} position={[-1.75, -0.208, -0.141]} />
        <mesh geometry={nodes.StaticMeshActor_38_StaticMeshComponent0.geometry} material={materials.Aluminum_Blurry__0} position={[-1.995, -0.29, -0.364]} />
        <mesh geometry={nodes.StaticMeshActor_39_StaticMeshComponent0.geometry} material={materials.Aluminum_Blurry__0} position={[1.304, -0.208, 0.549]} />
        <mesh geometry={nodes.StaticMeshActor_40_StaticMeshComponent0.geometry} material={materials.Aluminum_Blurry__0} position={[1.133, -0.208, -0.547]} />
        <mesh geometry={nodes.StaticMeshActor_41_StaticMeshComponent0.geometry} material={materials.Aluminum_Blurry__0} position={[1.304, -0.208, -0.547]} />
        <group position={[1.217, -0.208, 0.395]} >
          <mesh geometry={nodes.Cylinder030.geometry} material={materials.Plastic_Simple_Blurry_Black__0} />
          <mesh geometry={nodes.Cylinder030_1.geometry} material={materials.Aluminum_Blurry__0} />
        </group>
        <group position={[1.217, -0.208, -0.394]} >
          <mesh geometry={nodes.Cylinder031.geometry} material={materials.Plastic_Simple_Blurry_Black__0} />
          <mesh geometry={nodes.Cylinder031_1.geometry} material={materials.Aluminum_Blurry__0} />
        </group>
        <mesh geometry={nodes.StaticMeshActor_44_StaticMeshComponent0.geometry} material={materials.Plastic_Metallic_Black__0} position={[0.284, -0.181, -0.664]}  />
        <mesh geometry={nodes.StaticMeshActor_45_StaticMeshComponent0.geometry} material={materials.Plastic_Metallic_Black__0} position={[-2.165, -0.19, -0.653]} />
        <mesh geometry={nodes.StaticMeshActor_46_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__01} position={[1.639, -0.208, -0.654]} />
        <mesh geometry={nodes.StaticMeshActor_47_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__01} position={[0.302, -0.208, -0.673]} />
        <mesh geometry={nodes.StaticMeshActor_48_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__01} position={[-0.951, -0.208, -0.654]} />
        <mesh geometry={nodes.StaticMeshActor_52_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_white__01} position={[-0.364, -0.357, 0.001]}  />
        <mesh geometry={nodes.StaticMeshActor_53_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[0.257, -0.262, 0.151]} />
        <mesh geometry={nodes.StaticMeshActor_54_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[0.324, -0.267, 0.151]} />
        <mesh geometry={nodes.StaticMeshActor_55_StaticMeshComponent0.geometry} material={materials.Leather_white_16_50cm__0} position={[0.105, -0.006, 0.001]} />
        <mesh geometry={nodes.StaticMeshActor_56_StaticMeshComponent0.geometry} material={materials.Leather_black_16_50cm__0} position={[0.105, -0.006, 0.001]} />
        <mesh geometry={nodes.StaticMeshActor_57_StaticMeshComponent0.geometry} material={materials.Plastic_Metallic_Black__0} position={[0.402, -0.092, 0.116]} />
        <mesh geometry={nodes.StaticMeshActor_58_StaticMeshComponent0.geometry} material={materials.Aluminum_Blurry__0} position={[0.384, 0.032, 0.08]} />
        <group position={[0.333, -0.037, -0.113]}>
          <mesh geometry={nodes.Box039.geometry} material={materials.Plastic_Simple_Blurry_Black__0_2}  />
          <mesh geometry={nodes.Box039_1.geometry} material={materials.Aluminum_Blurry__0_2}  />
        </group>
        <group position={[0.35, -0.016, -0.091]}>
          <mesh geometry={nodes.Cylinder037.geometry} material={materials.Aluminum_Blurry__0_2} />
          <mesh geometry={nodes.Cylinder037_1.geometry} material={materials.Plastic_Simple_Blurry_Black__0_2} />
        </group>
        <mesh geometry={nodes.StaticMeshActor_61_StaticMeshComponent0.geometry} material={materials.Aluminum_Blurry__0} position={[0.375, 0.022, 0.08]} />
        <mesh geometry={nodes.StaticMeshActor_62_StaticMeshComponent0.geometry} material={materials.Plastic_Metallic_Black__0} position={[0.402, -0.092, 0.097]} />
        <mesh geometry={nodes.StaticMeshActor_63_StaticMeshComponent0.geometry} material={materials.Plastic_Metallic_Black__0} position={[0.402, -0.092, 0.077]} />
        <mesh geometry={nodes.StaticMeshActor_64_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[0.424, -0.16, -0.123]} />
        <mesh geometry={nodes.StaticMeshActor_65_StaticMeshComponent0.geometry} material={materials.Plastic_Metallic_Black__0} position={[0.427, -0.142, -0.123]} />
        <mesh geometry={nodes.StaticMeshActor_66_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[0.427, -0.177, -0.123]} />
        <mesh geometry={nodes.StaticMeshActor_67_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[0.33, -0.035, 0.08]} />
        <mesh geometry={nodes.StaticMeshActor_68_StaticMeshComponent0.geometry} material={materials.Aluminum_Blurry__0} position={[0.385, 0.034, 0.08]} />
        <mesh geometry={nodes.StaticMeshActor_69_StaticMeshComponent0.geometry} material={materials.Plastic_Metallic_Black__01} position={[1.895, -0.369, -0.016]} />
        <mesh geometry={nodes.StaticMeshActor_70_StaticMeshComponent0.geometry} material={materials.Aluminum_Blurry__0} position={[1.895, -0.212, -0.016]} />
        <mesh geometry={nodes.StaticMeshActor_71_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__01} position={[2.01, -0.033, 0.088]} />
        <mesh geometry={nodes.StaticMeshActor_72_StaticMeshComponent0.geometry} material={materials.Plastic_Metallic_Black__01} position={[1.895, -0.212, -0.016]} />
        <mesh geometry={nodes.StaticMeshActor_73_StaticMeshComponent0.geometry} material={materials.Plastic_Metallic_Black__01} position={[1.895, -0.212, -0.016]} />
        <mesh geometry={nodes.StaticMeshActor_74_StaticMeshComponent0.geometry} material={materials.Aluminum_Blurry__0} position={[1.895, -0.237, -0.016]} />
        <mesh geometry={nodes.StaticMeshActor_75_StaticMeshComponent0.geometry} material={materials.Aluminum_Blurry__0} position={[1.895, -0.237, -0.016]} />
        <mesh geometry={nodes.StaticMeshActor_76_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__01} position={[1.847, -0.035, -0.068]} />
        <mesh geometry={nodes.StaticMeshActor_77_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[1.531, -0.034, -0.16]} />
        <mesh geometry={nodes.StaticMeshActor_78_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[1.516, -0.035, -0.119]} />
        <group position={[1.895, -0.237, -0.016]}>
          <mesh geometry={nodes['002_LOW_0'].geometry} material={materials.Plastic_Metallic_Black__01} />
          <mesh geometry={nodes['002_LOW_0_1'].geometry} material={materials.Plastic_Metallic_Black__0_2} />
        </group>
        <mesh geometry={nodes.StaticMeshActor_80_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[1.432, -0.225, -0.142]} />
        <mesh name='Power Pole'
        ref={secFencRef}
        material-color={colors["Power Pole"]} geometry={nodes.StaticMeshActor_81_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0_4} position={[1.893, -0.361, -0.431]} />
        <mesh name='Power Pole'
        ref={secFencRef}
        material-color={colors["Power Pole"]} geometry={nodes.StaticMeshActor_82_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0_4} position={[1.855, -0.286, -0.431]} />
        <mesh name='Power Pole'
        ref={secFencRef}
        material-color={colors["Power Pole"]} geometry={nodes.StaticMeshActor_83_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0_4} position={[1.867, 0.509, -0.417]} />
        <mesh name='Power Pole'
        ref={secFencRef}
        material-color={colors["Power Pole"]} geometry={nodes.StaticMeshActor_84_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0_4} position={[1.858, 0.543, -0.418]} />
        <group position={[1.931, -0.344, -0.431]}>
          <mesh geometry={nodes.Cylinder072.geometry} material={materials.Plastic_Simple_Blurry_white__0_2} />
          <mesh name='Power Pole'
        ref={secFencRef}
        material-color={colors["Power Pole"]} geometry={nodes.Cylinder072_1.geometry} material={materials.Plastic_Simple_Blurry_Black__0_4} />
        </group>
        <mesh geometry={nodes.StaticMeshActor_86_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[1.846, -0.215, -0.432]}  />
        <mesh geometry={nodes.StaticMeshActor_87_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[1.846, -0.232, -0.432]} />
        <mesh geometry={nodes.StaticMeshActor_88_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[1.679, -0.235, -0.234]} />
        <mesh geometry={nodes.StaticMeshActor_89_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[1.679, -0.249, -0.234]} />
        <mesh name='Power Pole'
        ref={secFencRef}
        material-color={colors["Power Pole"]} geometry={nodes.StaticMeshActor_90_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0_4} position={[1.786, -0.282, -0.431]} />
        <mesh name='Power Pole'
        ref={secFencRef}
        material-color={colors["Power Pole"]} geometry={nodes.StaticMeshActor_91_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0_4} position={[1.68, -0.298, -0.429]} />
        <mesh geometry={nodes.StaticMeshActor_92_StaticMeshComponent0.geometry} material={materials.Plastic_Metallic_Black__01} position={[1.7, -0.258, -0.468]} />
        <mesh geometry={nodes.StaticMeshActor_93_StaticMeshComponent0.geometry} material={materials.Plastic_Metallic_Black__01} position={[1.7, -0.258, -0.39]} />
        <mesh geometry={nodes.StaticMeshActor_94_StaticMeshComponent0.geometry} material={materials.Plastic_Metallic_Black__01} position={[1.668, -0.342, -0.468]} />
        <mesh geometry={nodes.StaticMeshActor_95_StaticMeshComponent0.geometry} material={materials.Plastic_Metallic_Black__01} position={[1.668, -0.342, -0.39]} />
        <mesh geometry={nodes.StaticMeshActor_96_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[1.513, -0.225, 0.019]} />
        <mesh geometry={nodes.StaticMeshActor_97_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[1.468, -0.221, -0.094]} />
        <mesh geometry={nodes.StaticMeshActor_98_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[1.447, -0.222, -0.077]} />
        <mesh geometry={nodes.StaticMeshActor_99_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__0} position={[1.579, -0.229, -0.135]} />
        <mesh geometry={nodes.StaticMeshActor_109_StaticMeshComponent0.geometry} material={materials.Leather_black_16_50cm__0} position={[0.105, -0.006, 0.001]} />
        <mesh geometry={nodes.StaticMeshActor_110_StaticMeshComponent0.geometry} material={materials.Aluminum_Blurry__01} position={[1.199, -0.208, 0.623]} />
        <mesh geometry={nodes.StaticMeshActor_111_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__01} position={[0.145, -0.339, -0.585]} />
        <mesh geometry={nodes.StaticMeshActor_112_StaticMeshComponent0.geometry} material={materials.Plastic_Simple_Blurry_Black__01} position={[0.145, -0.339, 0.587]} />
        <mesh name='Poling Platform'
        ref={primFencRef}
        material-color={colors["Poling Platform"]} geometry={nodes.StaticMeshActor_113_StaticMeshComponent0.geometry} material={materials.Metal} position={[1.494, 0.769, 0.001]} />
        <mesh name='Poling Platform'
        ref={primFencRef}
        material-color={colors["Poling Platform"]} geometry={nodes.StaticMeshActor_114_StaticMeshComponent0.geometry} material={materials.Metal} position={[1.281, 0.279, 0.623]} />
        <mesh geometry={nodes.StaticMeshActor_115_StaticMeshComponent0.geometry} material={materials.Aluminum_Blurry__01} position={[1.486, -0.208, 0.623]}  />
        <mesh name='Poling Platform'
        ref={primFencRef}
        material-color={colors["Poling Platform"]} geometry={nodes.StaticMeshActor_116_StaticMeshComponent0.geometry} material={materials.Metal} position={[1.492, 0.281, 0.604]} />
        <mesh name='Poling Platform'
        ref={primFencRef}
        material-color={colors["Poling Platform"]} geometry={nodes.StaticMeshActor_117_StaticMeshComponent0.geometry} material={materials.Metal} position={[1.281, 0.279, -0.621]} />
        <mesh name='Poling Platform'
        ref={primFencRef}
        material-color={colors["Poling Platform"]} geometry={nodes.StaticMeshActor_118_StaticMeshComponent0.geometry} material={materials.Metal} position={[1.571, 0.279, -0.621]} />
        <mesh geometry={nodes.StaticMeshActor_119_StaticMeshComponent0.geometry} material={materials.Aluminum_Blurry__01} position={[1.199, -0.208, -0.621]}  />
        <mesh geometry={nodes.StaticMeshActor_120_StaticMeshComponent0.geometry} material={materials.Aluminum_Blurry__01} position={[1.486, -0.208, -0.621]} />
        <mesh name='Poling Platform'
        ref={primFencRef}
        material-color={colors["Poling Platform"]} geometry={nodes.StaticMeshActor_121_StaticMeshComponent0.geometry} material={materials.Metal} position={[1.492, 0.281, -0.603]} />
        <group position={[1.494, 0.769, 0.001]}>
          <mesh geometry={nodes.Rectangle004.geometry} material={materials.Object_2390314d_9d4d_4dbb_b139_60ab16757409} />
          <mesh geometry={nodes.Rectangle004_1.geometry} material={materials.Plastic_Simple_Blurry_Black__01} />
        </group>
        <mesh geometry={nodes.StaticMeshActor_123_StaticMeshComponent0.geometry} material={materials.Metal} position={[1.498, .767, 0.001]}  />
        <mesh geometry={nodes.StaticMeshActor_124_StaticMeshComponent0.geometry} material={materials.Plastic_Metallic_Black__0} position={[-0.994, -0.325, 0.001]} />
        <mesh name='Poling Platform'
        ref={primFencRef}
        material-color={colors["Poling Platform"]} geometry={nodes.StaticMeshActor_125_StaticMeshComponent0.geometry} material={materials.Metal} position={[1.691, 0.564, 0.586]}  />
        <mesh name='Poling Platform'
        ref={primFencRef}
        material-color={colors["Poling Platform"]} geometry={nodes.StaticMeshActor_126_StaticMeshComponent0.geometry} material={materials.Metal} position={[1.691, 0.564, -0.585]}  />
        <mesh name='Poling Platform'
        ref={primFencRef}
        material-color={colors["Poling Platform"]} geometry={nodes.StaticMeshActor_127_StaticMeshComponent0.geometry} material={materials.Metal} position={[1.814, 0.766, 0.001]} />
        <group position={[1.82, 0.769, 0.001]}>
          <mesh geometry={nodes.Cylinder085.geometry} material={materials.Plastic_Simple_Blurry_Black__01} />
          <mesh geometry={nodes.Cylinder085_1.geometry} material={materials.Aluminum_Blurry__01} />
        </group>
        <mesh geometry={nodes.StaticMeshActor_129_StaticMeshComponent0.geometry} material={materials.Plastic_Metallic_white_0} position={[-0.007, -0.246, 0.001]} />
        <mesh geometry={nodes.StaticMeshActor_130_StaticMeshComponent0.geometry} material={materials.Plastic_Metallic_Black__0} position={[1.514, 0.772, 0.001]} />
        <mesh name='Poling Platform'
        ref={primFencRef}
        material-color={colors["Poling Platform"]} geometry={nodes.StaticMeshActor_131_StaticMeshComponent0.geometry} material={materials.Metal} position={[1.571, 0.279, 0.623]} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/skimmer-skiff-fourteen.glb')
